name: CI
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name to re-build ?
        required: true
        type: string
  push:
  pull_request:
jobs:
  build:
    env:
      branch: ${{ inputs.branch || github.head_ref || github.ref_name }}
      stage: ${{ inputs.branch == 'main' && 'latest' || github.ref_name == 'main' && 'latest' || 'next' }}
      ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.branch }}
          token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
          
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: Dont-code
          email: developer@dont-code.net
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: node common/scripts/install-run-rush.js install
      - name: Build
        run: |
          node common/scripts/install-run-rush.js build-prod
      - name: Tests
        run: node common/scripts/install-run-rush.js test
      - name: E2e Tests
        run: node common/scripts/install-run-rush.js e2e-test --browser chrome
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: sandbox-e2e-test.log
          path: libs/ng-sandbox/sandbox-e2e-test.log
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: sandbox-e2e-test.error.log
          path: libs/ng-sandbox/sandbox-e2e-test.error.log
