name: CI
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name to re-build ?
        required: true
        type: string
  push:
  pull_request:
jobs:
  build:
    env:
      branch: ${{ inputs.branch || github.head_ref || github.ref_name }}
      stage: ${{ inputs.branch == 'main' && 'latest' || github.ref_name == 'main' && 'latest' || 'next' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
          ref: ${{ env.branch }}
          token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
          
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: Dont-code
          email: developer@dont-code.net
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush Tests
        run: node common/scripts/install-run-rush.js test
      - name: Rush E2e Tests
        run: node common/scripts/install-run-rush.js e2e-test
      - name: Rush rebuild
        run: |
        node common/scripts/install-run-rush.js clean
        node common/scripts/install-run-rush.js build-prod
