name: Release
on:
  workflow_dispatch:
    inputs:
      next:
        description: Is it a dev / next release ?
        required: true
        type: boolean
      deploy:
        description: Deploy to public website?
        required: true
        type: boolean
jobs:
  build:
    env:
      branch: ${{ inputs.next == true && 'Development' || 'main' }}
      stage: ${{ inputs.next == true && 'next' || 'latest' }}
      build: ${{ inputs.next == true && 'next' || 'production' }}
      ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, chrome]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ env.branch }}
          token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
          
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: Dont-code
          email: developer@dont-code.net
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          node common/scripts/install-run-rush.js install
      - name: Build
        run: |
          node common/scripts/install-run-rush.js build-deploy-${{ env.stage }}
      - name: Deploy to github pages as ${{env.stage}}
        if: ${{ success() && (matrix.browser == 'chromium') && ( inputs.deploy == true ) }}
        uses: gcollin/ghaction-github-pages@main
        with:
          repo: dont-code/plugins
          target_branch: gh-pages # The branch the action should deploy to.
          build_dir: plugins/standard/dist/apps/plugin-tester
          keep_history: false
          multiple_sites: true
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
      - if: ${{ success() && (matrix.browser == 'chromium') && ( inputs.deploy == true ) }}
        uses: gcollin/ghaction-github-pages@main
        with:
          repo: dont-code/plugin-seed
          target_branch: gh-pages # The branch the action should deploy to.
          build_dir: plugins/seed/dist/apps/seed-tester
          keep_history: false
          multiple_sites: true
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
      - if: ${{ success() && (matrix.browser == 'chromium') && ( inputs.deploy == true ) }}
        uses: gcollin/ghaction-github-pages@main
        with:
          repo: dont-code/plugin-rest
          target_branch: gh-pages # The branch the action should deploy to.
          build_dir: plugins/rest/dist/apps/rest-tester
          keep_history: false
          multiple_sites: true
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
      - if: ${{ success() && (matrix.browser == 'chromium') && ( inputs.deploy == true ) }}
        uses: gcollin/ghaction-github-pages@main
        with:
          repo: dont-code/plugin-report
          target_branch: gh-pages # The branch the action should deploy to.
          build_dir: plugins/report/dist/apps/report-tester
          keep_history: false
          multiple_sites: true
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
      - if: ${{ success() && (matrix.browser == 'chromium') && ( inputs.deploy == true ) }}
        uses: gcollin/ghaction-github-pages@main
        with:
          repo: dont-code/plugin-commerce
          target_branch: gh-pages # The branch the action should deploy to.
          build_dir: plugins/commerce/dist/apps/commerce-tester
          keep_history: false
          multiple_sites: true
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
      - if: ${{ success() && (matrix.browser == 'chromium') && ( inputs.deploy == true ) }}
        uses: gcollin/ghaction-github-pages@main
        with:
          repo: dont-code/ide-ui
          target_branch: gh-pages # The branch the action should deploy to.
          build_dir: apps/ide-ui/dist/apps/ide-ui
          keep_history: false
          multiple_sites: true
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
      - if: ${{ success() && (matrix.browser == 'chromium') &&( inputs.deploy == true ) }}
        uses: gcollin/ghaction-github-pages@main
        with:
          repo: dont-code/preview-ui
          target_branch: gh-pages # The branch the action should deploy to.
          build_dir: apps/preview-ui/dist/apps/preview-ui
          keep_history: false
          multiple_sites: true
          jekyll: false
        env:
          GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
